-- Bridge3 Academy — Phase 6: Classroom (lesson notes, resources, progress)
-- Run this once in Supabase → SQL Editor → New Query → paste → Run.

alter table lessons add column if not exists instructor_name text;
alter table lessons add column if not exists notes text;

-- Files an admin (Phase 11) can attach to a lesson. Empty for now — no
-- admin upload tool exists yet, but the classroom page is built to show
-- these the moment they exist, with no further changes needed later.
create table if not exists lesson_resources (
  id uuid primary key default gen_random_uuid(),
  lesson_id uuid not null references lessons(id) on delete cascade,
  file_name text not null,
  storage_path text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_lesson_resources_lesson on lesson_resources (lesson_id);

alter table lesson_resources enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where tablename = 'lesson_resources' and policyname = 'authenticated can view lesson resources') then
    create policy "authenticated can view lesson resources"
      on lesson_resources for select
      to authenticated
      using (true);
  end if;
end $$;

-- One row per lesson a student has completed. Unlike the course catalog,
-- students DO write to this table directly — but only their own rows,
-- enforced below.
create table if not exists student_progress (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references profiles(id) on delete cascade,
  lesson_id uuid not null references lessons(id) on delete cascade,
  completed_at timestamptz not null default now(),
  unique (student_id, lesson_id)
);

create index if not exists idx_student_progress_student on student_progress (student_id);
create index if not exists idx_student_progress_lesson on student_progress (lesson_id);

alter table student_progress enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where tablename = 'student_progress' and policyname = 'students can view their own progress') then
    create policy "students can view their own progress"
      on student_progress for select
      to authenticated
      using (auth.uid() = student_id);
  end if;

  if not exists (select 1 from pg_policies where tablename = 'student_progress' and policyname = 'students can mark their own lessons complete') then
    create policy "students can mark their own lessons complete"
      on student_progress for insert
      to authenticated
      with check (auth.uid() = student_id);
  end if;

  if not exists (select 1 from pg_policies where tablename = 'student_progress' and policyname = 'students can unmark their own lessons complete') then
    create policy "students can unmark their own lessons complete"
      on student_progress for delete
      to authenticated
      using (auth.uid() = student_id);
  end if;
end $$;

-- Add sample instructor + notes content to existing seed lessons, so the
-- classroom page has real content to test against. Deliberately NOT
-- seeding a video_url — that would mean linking to a real external video
-- without being certain it's appropriate/permanent, so the video player's
-- empty state is what you'll see until a real video is attached via the
-- Admin Panel (Phase 11) or Storage.
update lessons set
  instructor_name = 'Oyetundun Taiwo',
  notes = 'A plain-language introduction to what blockchain actually is, why it matters, and the core idea of a decentralized ledger.'
where title = 'What is Blockchain?';

update lessons set
  instructor_name = 'Oyetundun Taiwo',
  notes = 'Covers where Bitcoin came from, how it works at a high level, and why it started the broader crypto economy.'
where title = 'Bitcoin Basics';

-- file requires a signed URL generated by our own code, not a bare public
-- link, since only signed-in students should access course materials.
insert into storage.buckets (id, name, public)
values ('lesson-resources', 'lesson-resources', false)
on conflict (id) do nothing;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage' and tablename = 'objects'
      and policyname = 'authenticated can read lesson resources'
  ) then
    create policy "authenticated can read lesson resources"
      on storage.objects for select
      to authenticated
      using (bucket_id = 'lesson-resources');
  end if;
end $$;
